runtime: python39
service: default

env_variables:
  PYTHON_ENV: "production"
  REGION: "asia-south2"

instance_class: F1

automatic_scaling:
  target_cpu_utilization: 0.65
  min_instances: 0
  max_instances: 1
  target_throughput_utilization: 0.6
  max_concurrent_requests: 10

handlers:
- url: /static
  static_dir: static
  secure: always

- url: /.*
  script: auto
  secure: always

entrypoint: gunicorn -b :$PORT app:app
